_format_version: "3.0"
_transform: true

# https://docs.konghq.com/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/#declarative-configuration-format

services:
  - name: account-service
    url: http://account:8002
    routes:
        - paths:
          - /account
          strip_path: true
  - name: performance-service
    url: http://viz:8003
    routes:
        - paths:
          - /performance
          strip_path: true
  - name: task-service
    url: http://task:8004
    routes:
        - paths:
          - /task
          strip_path: true
  - name: notification-service
    url: http://notification:8005
    routes:
        - paths:
          - /notification
          strip_path: true