-- Add up migration script here
ALTER TABLE task
ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE routine
ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE habit
ADD COLUMN created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;